#!/usr/bin/env bash
# Script to configure Nginx with custom header

sudo apt update
sudo apt install -y nginx

hostname=$(hostname)

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }
    add_header X-Served-By $hostname;

}" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo systemctl restart nginx
sudo systemctl enable nginx
service nginx start

echo "Nginx configured successfully with custom HTTP response header."
