#!/usr/bin/env bash
# Script to install and config HAproxy

apt-get -y install haproxy
echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 288478-web-01 18.209.223.36:80 check
   server 288478-web-02 54.146.87.142:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
