#!/usr/bin/env bash
# Script that displays listening ports

echo "Active Internet connections (only servers)"
echo "Proto	Recv-Q	Send-Q	Local Address	Foreign Address	State	PID/Program name"

ss -tlnp | awk 'NR>1 {print $1, $2, $4, $5, $6, $7}' | column -t
ss -ulnp | awk 'NR>1 {print $1, $2, $4, $5, $6, $7}' | column -t

echo
echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags	Type	State	I-Node	PID/Program name	Path"

ss -lx | awk 'NR>1 {print $1, $2, $4, $5, $6, $7, $8}' | column -t
