#!/usr/bin/env bash
# Script to configure server

# Update Nginx configuration to listen on port 80
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Restart Nginx
sudo systemctl restart nginx

echo "Nginx configuration updated and restarted successfully."
