#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

pidfile="/var/run/myscript.pid"

# Function to handle SIGTERM and SIGQUIT signals
cleanup()
{
    echo "Cleaning up..."
    rm -f "$pidfile"
    exit 0
}

# handle SIGINT signal
handle_sigint()
{
    echo "Y U no love me?!"
}

# Function to handle SIGTERM signal
handle_sigterm()
{
    echo "I hate the kill command"
}

# Trap signals
trap cleanup SIGQUIT SIGTERM
trap handle_sigint SIGINT

# Save PID to pidfile
echo $$ > "$pidfile"

# Display To infinity and beyond indefinitely
while true
do
    echo "To infinity and beyond"
    sleep 2
done
