#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely
# sleep 2 in between each iteration.
# Displays "I am invincible!!!" if SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
