#!/usr/bin/env bash
#While loop with case statement

i=1

while [ $i -le 20 ]
do
    case $i in
        4)
            echo "$i and then bad luck from china"
            ;;
        9)
            echo "$i and then bad luck from japan"
            ;;
        17)
            echo "$i and then bad luck from italy"
            ;;
        *)
            echo $i
            ;;
    esac

    ((i++))
done
