#!/usr/bin/env bash
# Bash script that prints time

hours=0

while [ $hours -le 12 ]
do
    echo "Hour: $hours"
    
    minutes=1
    while [ $minutes -le 59 ]
    do
        printf "%d\n" $minutes
        ((minutes++))
    done

    ((hours++))
done

