#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.

sudo sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
sudo sed -i "s/listen 80 default_server;/listen 8080 default_server;/" /etc/nginx/sites-available/default
sudo sed -i "s/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/" /etc/nginx/sites-available/default

sudo systemctl stop apache2
sudo systemctl start nginx
